name: Release Please

on:
  push:
    branches: [main]

permissions: {}

jobs:
  release-please:
    permissions:
      contents: write
      pull-requests: write
    uses: dryvist/.github/.github/workflows/_release-please.yml@26e28bf87868d0c71119bf8ce914325dbd468cdc # v1.11.0
    secrets:
      GH_ACTION_RELEASE_PLEASE_PRIVATE_KEY: ${{ secrets.GH_ACTION_RELEASE_PLEASE_PRIVATE_KEY }}
