name: Release Please

on:
  push:
    branches: [main]

permissions: {}

jobs:
  release-please:
    permissions:
      contents: write
      pull-requests: write
    uses: dryvist/.github/.github/workflows/_release-please.yml@c4501ea67ce4469a5cc95216c9a989516da2adb8 # v1.10.0
    secrets:
      GH_ACTION_RELEASE_PLEASE_PRIVATE_KEY: ${{ secrets.GH_ACTION_RELEASE_PLEASE_PRIVATE_KEY }}
