name: Release Please

on:
  push:
    branches: [main]

permissions: {}

jobs:
  release-please:
    permissions:
      contents: write
      pull-requests: write
    uses: dryvist/.github/.github/workflows/_release-please.yml@6a0ffc17fe67dfad4c5d2541cdf630f2e2376991 # v1.11.1
    secrets:
      GH_ACTION_RELEASE_PLEASE_PRIVATE_KEY: ${{ secrets.GH_ACTION_RELEASE_PLEASE_PRIVATE_KEY }}
